ROOT=../../..

test:
	@./test_value_instance.py
	@./test_bir_struct.py
	@./test_metadata_instance.py
	@./test_table.py
	@./test_packet_instance.py
	@./test_parser.py
	@./test_instance.py
	@./test_instance_mpls.py

